import React from 'react'

const Privacy = () => {
    
    return (
        document.title="Privacy Terms"
        <div className="mt-6">
            <h1 className="font-inter text-center underline text-3xl">Privacy Policy</h1>
            <div className="w-4/5 mx-auto mt-8 text-lg font-inter font-semibold">
<p><strong>Last Updated: </strong>July 22, 2020</p><p><strong>INTRODUCTION</strong></p><p>This Privacy Policy governs the way <strong>TriviaKing</strong> (“<strong>TriviaKing</strong>”, “we”, “our”, or, “<strong>Company</strong>”) collects, uses, maintains and discloses information collected from and about you as well as your rights and choices regarding such information. It applies to your use of any online service location that posts a link to this Privacy Policy including, without limitation, the Trivia Maker website or application (“<strong>Site</strong>”) and any offline location that makes this Privacy Policy available to you. This Privacy Policy does not describe information collection practices on other websites, including those linked to or from our website. Please see the “Other Parties” section below for more details.</p><p>If you have any questions or wish to exercise your rights and choices, please contact us as set out in the “Complaints and Contact Information” section. If you are a Nevada resident, California resident, or data subject in Europe, please see the additional disclosures at the end of this Privacy Policy.</p><p><strong>PURPOSE OF THIS PRIVACY POLICY</strong></p><p>The purpose of this Privacy Policy is to help you better understand how we store, collect, and process your information. In particular, by using the Site or interacting with us offline, you agree to our <a href="/terms" target="_blank" rel="noopener noreferrer"><strong><u>Terms of Use</u></strong></a> and you consent to our collection, use, and disclosure of your information, and other activities as described in this Privacy Policy, including any updates or revisions to this Privacy Policy. If you do not agree, discontinue use of the Site.</p><p><strong>CHANGES TO THIS PRIVACY POLICY</strong></p><p>TriviaKing has the discretion to update this Privacy Policy at any time. When we do, we will revise the updated date. You acknowledge and agree that it is your responsibility to review this Privacy Policy periodically and become aware of modifications. Your continued use of the Site indicates your consent to the Privacy Policy then posted.</p><p><strong>INFORMATION TriviaKing COLLECTS</strong></p><p>When you engage in certain activities via the Site, including but not limited to creating an account, sending feedback, or otherwise participating in the Site, or interacting with us offline, we collect certain information about you. We collect the following categories of information:</p>
<ol><li>Account Data, including your username, password, and information for authentication and account access.</li></ol><ul><li>Billing Data, including your payment instrument number (such as a credit or debit card number), expiration date, and security code as necessary to process your payments.</li></ul><ul><li>Contact Data, including your email address.</li><li>Profile Data, including games you created, your collections, and your favorites.</li><li>Content, including content within any messages you send to us (such as feedback and questions to customer support).</li></ul><p>You may choose to voluntarily provide other information to us that we do not request, and, in such instances, you are solely responsible for such information.</p>
           </div>
        </div>
    );
};

export default Privacy;

